<a href="https://colab.research.google.com/github/santhapurharsha/Pytorch-Deep-Learning-for-CV/blob/master/LinearRegression_Pytorch/LinearRegression_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip3 install torch

In [0]:
import torch

In [0]:
w = torch.tensor(3.0, requires_grad = True) # weights
b = torch.tensor(1.0, requires_grad = True)  # bias



In [0]:
def forward(x):
  y = w*x + b  #Linear Model
  return y

In [6]:
x = torch.tensor(2)
forward(x)

tensor(7., grad_fn=<AddBackward0>)

In [7]:
x = torch.tensor([[4],[7]])
forward(x)

tensor([[13],
        [22]], grad_fn=<AddBackward0>)

In [0]:
#Linear Classes


In [0]:
from torch.nn import Linear


In [9]:
torch.manual_seed(1)  # The reason we are doing this is, when constructing our model with the linear class, it will be given random
                      # values for the linear class which makes sense since recall. The seed can be anything that we want to be
model = Linear(in_features =1, out_features = 1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [11]:
x = torch.tensor([2.0])
print(model(x))   # model(x) returns a prediction for given x


tensor([0.5891], grad_fn=<AddBackward0>)


In [12]:
x = torch.tensor([[2.0],[3.3]])
print(model(x))   # model(x) returns a prediction for given x


tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)


In [0]:
# custom module
import torch.nn as nn

In [0]:
#class LR(nn.Module): # In this case the linear regression model class will be a subclass of nn Module therby inherit methods and variables
                     # from this parent class and when dealing with class inheritance one should be mindful of calling super().__init__ which simply
                     # allows for more freedom in the use of multiple inheritence from parent classes.
  #def __init__(self, input_size, output_size)  # we use this constructor to initialize new instances of this class
                                               # The first argument for our initializer here is usually self, self 
                                               # simply represents the instance of class, the object that's yet to be intialized 
      
  # self.linear           represents the instance of the class, the object that we intend to initialize and it will be set to nn.Linear
class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)
  def forward(self,x):
    pred = self.linear(x)
    return pred
  
   

In [26]:
torch.manual_seed(1)
model = LR(1,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [27]:
x = torch.tensor([1.0])
print(model.forward(x))

tensor([0.0739], grad_fn=<AddBackward0>)
