<a href="https://colab.research.google.com/github/santhapurharsha/Pytorch-Deep-Learning-for-CV/blob/master/Tensors_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch


In [0]:
import torch
import numpy as np


In [9]:
v = torch.tensor([1,2,3, 4, 5, 6])
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [7]:
print(v.dtype)

torch.int64


In [8]:
print(v[0])

tensor(1)


In [10]:
print(v[1:4])

tensor([2, 3, 4])


In [11]:
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [13]:
f = torch.torch.FloatTensor([1,2,3,4,5,6])
print(f)

tensor([1., 2., 3., 4., 5., 6.])


In [14]:
print(f.dtype)

torch.float32


In [16]:
print(f.size())

torch.Size([6])


In [18]:
v.view(6,1)
#tensor is reshaped to have six rows in one column

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [19]:
v.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [21]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [22]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
