<a href="https://colab.research.google.com/github/santhapurharsha/Pytorch-Deep-Learning-for-CV/blob/master/Tensors/tensors_dimensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip3 install torch

In [0]:
import torch

In [5]:
one_d = torch.arange(0,9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
two_d = one_d.view(3,3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [0]:
two_d.dim()

2

In [0]:
two_d[0, 0]

tensor(0)

In [0]:
two_d[1, 2]

tensor(5)

In [7]:
x = torch.arange(0, 18).view(3,3,2) #Ability to change the shape of tensor according to a tuple of integers 
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [8]:
x[1,1,1]

tensor(9)

In [10]:
y = torch.arange(0, 18).view(3,2,3) #Ability to change the shape of tensor according to a tuple of integers 
y

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [11]:
y[1,1,1]

tensor(10)

In [13]:
y[1, 0:2, 0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [14]:
y[2, 0:2, 0:3]

tensor([[12, 13, 14],
        [15, 16, 17]])

In [15]:
y[0, 0:2, 0:3]

tensor([[0, 1, 2],
        [3, 4, 5]])