<a href="https://colab.research.google.com/github/santhapurharsha/Pytorch-Deep-Learning-for-CV/blob/master/tensors_dimensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
!pip3 install torch

In [0]:
import torch

In [46]:
one_d = torch.arange(0,9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
two_d = one_d.view(3,3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [49]:
two_d.dim()

2

In [50]:
two_d[0, 0]

tensor(0)

In [51]:
two_d[1, 2]

tensor(5)

In [53]:
x = torch.arange(0, 18).view(3,3,2) #Ability to change the shape of tensor according to a tuple of integers 
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])