<a href="https://colab.research.google.com/github/santhapurharsha/Pytorch-Deep-Learning-for-CV/blob/master/Tensors/tensors_dimensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip3 install torch

In [0]:
import torch

In [0]:
one_d = torch.arange(0,9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
two_d = one_d.view(3,3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [0]:
two_d.dim()

2

In [0]:
two_d[0, 0]

tensor(0)

In [0]:
two_d[1, 2]

tensor(5)

In [0]:
x = torch.arange(0, 18).view(3,3,2) #Ability to change the shape of tensor according to a tuple of integers 
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [0]:
x[1,1,1]

tensor(9)

In [0]:
y = torch.arange(0, 18).view(3,2,3) #Ability to change the shape of tensor according to a tuple of integers 
y

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [0]:
y[1,1,1]

tensor(10)

In [0]:
y[1, 0:2, 0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [0]:
y[2, 0:2, 0:3]

tensor([[12, 13, 14],
        [15, 16, 17]])

In [0]:
y[0, 0:2, 0:3]

tensor([[0, 1, 2],
        [3, 4, 5]])

In [4]:
#Multiplication
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,3)
mat_a


tensor([[0, 3, 5],
        [5, 5, 2]])

In [5]:
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [6]:
torch.matmul(mat_a, mat_b)

tensor([[ 29, -16],
        [ 38,   6]])

In [7]:
mat_a @ mat_b

tensor([[ 29, -16],
        [ 38,   6]])

In [9]:
#differentiation
x = torch.tensor(2.0, requires_grad = True)
y = 9*x**4 + 2*x**3 + 3*x**2 + 6*x + 1
y.backward()
x.grad

tensor(330.)

In [10]:
# Partial derivative
x = torch.tensor(1.0, requires_grad = True)
z = torch.tensor(2.0, requires_grad = True)
y = x**2 + z**3
y.backward()
x.grad

tensor(2.)

In [11]:
z.grad

tensor(12.)